name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Code compiles
      id: code-compiles
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Code compiles
        setup-command: ''
        command: gradle compileJava
        timeout: 2
    - name: Tests run successfully
      id: tests-run-successfully
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Tests run successfully
        setup-command: ''
        command: gradle test
        timeout: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CODE-COMPILES_RESULTS: "${{steps.code-compiles.outputs.result}}"
        TESTS-RUN-SUCCESSFULLY_RESULTS: "${{steps.tests-run-successfully.outputs.result}}"
      with:
        runners: code-compiles,tests-run-successfully
